FROM nginx:1.11
ADD ./compose/production/nginx/nginx.conf /etc/nginx/nginx.conf
ADD ./compose/production/nginx/ssl/mydomain.com.crt /etc/ssl/certs/mydomain.com.crt
ADD ./compose/production/nginx/ssl/mydomain.com.key /etc/ssl/private/mydomain.com.key
